(()=>{
  'use strict';
  const SUITE_VERSION='1.3',FIELD_KEY='hockeyGoalieStatsV3',TRIALS_KEY='hgt-data-driven-selection-v1';
  const RECORDER_KEYS=['gsr_v129_state','gsr_v128_state','gsr_v127_state','gsr_v126_state','goalieStatsRecorderMasterData','gsr_last_forced_refresh'];
  const AGE_GROUPS=['U10','U11','U13','U14','U16','U19','U20','Senior','Open','Not specified'],LEVELS=['School','Club','Provincial','National','Other','Not specified'],TIERS=['A / 1st','B / 2nd','C / 3rd','D / 4th','Other','Not specified'];
  const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid=()=>{try{return'id_'+crypto.randomUUID()}catch{return'id_'+Date.now().toString(36)+Math.random().toString(36).slice(2)}},clone=value=>JSON.parse(JSON.stringify(value));
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}},field=()=>{const value=read(FIELD_KEY,{goalies:[]});if(!Array.isArray(value.goalies))value.goalies=[];return value},writeField=value=>localStorage.setItem(FIELD_KEY,JSON.stringify(value));
  const option=(value,selected)=>`<option${value===selected?' selected':''}>${esc(value)}</option>`;
  let toastTimer,teamDraft=[],pendingRestore=null;
  function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
  function initials(name){return String(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
  function dobLabel(value){if(!value)return'Date of birth not recorded';const d=new Date(value+'T12:00:00');return Number.isNaN(d.getTime())?value:d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
  function ageAtJanOne(dob){if(!dob)return null;const birth=new Date(dob+'T12:00:00Z');if(Number.isNaN(birth.getTime()))return null;const year=new Date().getUTCFullYear(),birthdayAfterJanOne=birth.getUTCMonth()>0||birth.getUTCDate()>1;return year-birth.getUTCFullYear()-(birthdayAfterJanOne?1:0)}
  function calculatedAgeGroup(dob){const age=ageAtJanOne(dob);if(age===null)return'Not specified';if(age<=9)return'U10';if(age<=10)return'U11';if(age<=12)return'U13';if(age<=13)return'U14';if(age<=15)return'U16';if(age<=18)return'U19';if(age<=19)return'U20';return'Senior'}
  function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+page));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('sidebar').classList.remove('open');location.hash=page==='home'?'':page;if(page==='goalies')renderGoalies();if(page==='benchmarking')renderBenchmarking();if(page==='backup')refreshBackupGoalies();window.scrollTo(0,0)}
  document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',()=>showPage(x.dataset.page)));document.querySelectorAll('[data-go]').forEach(x=>x.addEventListener('click',()=>showPage(x.dataset.go)));$('menuButton').addEventListener('click',()=>$('sidebar').classList.toggle('open'));
  function normalizeProfiles(g){const profiles=Array.isArray(g.teamProfiles)?g.teamProfiles:[];if(!profiles.length&&Array.isArray(g.teams))g.teamProfiles=g.teams.filter(Boolean).map((name,i)=>({id:uid(),name,sportType:'field_hockey',ageGroup:g.ageGroup||'Not specified',level:'Not specified',tier:'Not specified',isDefault:i===0}));else g.teamProfiles=profiles.map((p,i)=>({id:p.id||uid(),name:p.name||'',sportType:p.sportType||'field_hockey',ageGroup:p.ageGroup||'Not specified',level:p.level||'Not specified',tier:p.tier||'Not specified',isDefault:Boolean(p.isDefault??(p.default??i===0))}));return g.teamProfiles}
  function profileSummary(g){const profiles=normalizeProfiles(g);return profiles.length?profiles.map(p=>`${p.name||'Unnamed team'} · ${p.sportType==='indoor_hockey'?'Indoor':'Field'} · ${p.ageGroup}`).join(' | '):'No team profiles'}
  function renderGoalies(){const db=field();$('goalieList').innerHTML=db.goalies.length?db.goalies.map(g=>`<div class="goalie-row"><div class="goalie-avatar">${esc(initials(g.name))}</div><div class="goalie-main"><b>${esc(g.name||'Unnamed Goalie')}</b><small>${esc(g.gender||'Not specified')} · ${esc(dobLabel(g.dob))} · ${esc(g.ageGroup||calculatedAgeGroup(g.dob))}</small><small>${esc(profileSummary(g))}</small></div><button class="secondary" type="button" data-edit-goalie="${esc(g.id)}">Edit</button></div>`).join(''):'<div class="empty">No shared goalkeepers enrolled yet.</div>';document.querySelectorAll('[data-edit-goalie]').forEach(button=>button.addEventListener('click',()=>editGoalie(button.dataset.editGoalie)))}
  function newTeamProfile(){return{id:uid(),sportType:'field_hockey',name:'',ageGroup:$('goalieAgeGroup').value||'Not specified',level:'Not specified',tier:'Not specified',isDefault:!teamDraft.some(p=>p.sportType==='field_hockey')}}
  function renderTeamProfiles(){const root=$('teamProfiles');root.innerHTML=teamDraft.length?teamDraft.map((p,i)=>`<div class="team-profile" data-team-index="${i}"><label class="profile-name">Team Name<input data-team-field="name" value="${esc(p.name)}" placeholder="Enter the full team name"></label><label class="profile-sport">Sport<select data-team-field="sportType"><option value="field_hockey"${p.sportType!=='indoor_hockey'?' selected':''}>Field Hockey</option><option value="indoor_hockey"${p.sportType==='indoor_hockey'?' selected':''}>Indoor Hockey</option></select></label><label class="profile-age">Age Group<select data-team-field="ageGroup">${AGE_GROUPS.map(x=>option(x,p.ageGroup)).join('')}</select></label><label class="profile-level">Level<select data-team-field="level">${LEVELS.map(x=>option(x,p.level)).join('')}</select></label><label class="profile-tier">Tier<select data-team-field="tier">${TIERS.map(x=>option(x,p.tier)).join('')}</select></label><label class="default-wrap"><input type="checkbox" data-team-field="isDefault"${p.isDefault?' checked':''}> Default team for this sport</label><button class="danger team-remove" type="button" data-remove-team="${i}">Remove Team</button></div>`).join(''):'<div class="empty">No team profiles yet. Select Add Team to create one.</div>';root.querySelectorAll('[data-team-field]').forEach(control=>control.addEventListener('change',()=>{const index=Number(control.closest('[data-team-index]').dataset.teamIndex),key=control.dataset.teamField;teamDraft[index][key]=control.type==='checkbox'?control.checked:control.value;if(key==='isDefault'&&control.checked){teamDraft.forEach((p,j)=>{if(j!==index&&p.sportType===teamDraft[index].sportType)p.isDefault=false});renderTeamProfiles()}}));root.querySelectorAll('[data-remove-team]').forEach(button=>button.addEventListener('click',()=>{teamDraft.splice(Number(button.dataset.removeTeam),1);renderTeamProfiles()}))}
  function clearGoalieForm(){$('goalieId').value='';$('goalieName').value='';$('goalieDob').value='';$('goalieAgeGroup').value='Not specified';$('goalieGender').value='Male';teamDraft=[];$('goalieFormTitle').textContent='Enroll New Goalie';renderTeamProfiles();$('goalieName').focus()}
  function editGoalie(id){const g=field().goalies.find(x=>String(x.id)===String(id));if(!g)return;$('goalieId').value=g.id;$('goalieName').value=g.name||'';$('goalieDob').value=g.dob||'';$('goalieAgeGroup').value=g.ageGroup||calculatedAgeGroup(g.dob);$('goalieGender').value=g.gender||'Male';teamDraft=clone(normalizeProfiles(g));$('goalieFormTitle').textContent='Edit Shared Goalie';renderTeamProfiles()}
  $('goalieDob').addEventListener('input',()=>{$('goalieAgeGroup').value=calculatedAgeGroup($('goalieDob').value)});$('addTeamProfile').addEventListener('click',()=>{teamDraft.push(newTeamProfile());renderTeamProfiles()});$('newGoalieButton').addEventListener('click',clearGoalieForm);
  $('goalieForm').addEventListener('submit',event=>{event.preventDefault();const db=field(),id=$('goalieId').value;let g=db.goalies.find(x=>String(x.id)===String(id));if(!g){g={id:uid(),matches:[],teams:[],teamProfiles:[],benchmarkConsent:'undecided',benchmarkGoalieId:'goalie_'+uid(),centralProfile:true};db.goalies.push(g)}const now=new Date().toISOString(),profiles=teamDraft.filter(p=>p.name.trim()).map(p=>({...p,name:p.name.trim(),updatedAt:now}));['field_hockey','indoor_hockey'].forEach(sport=>{const list=profiles.filter(p=>p.sportType===sport);if(list.length&&!list.some(p=>p.isDefault))list[0].isDefault=true});Object.assign(g,{name:$('goalieName').value.trim()||'Unnamed Goalie',dob:$('goalieDob').value,ageGroup:$('goalieAgeGroup').value||calculatedAgeGroup($('goalieDob').value),gender:$('goalieGender').value,teamProfiles:profiles,teams:profiles.filter(p=>p.sportType==='field_hockey').map(p=>p.name),centralProfile:true,updatedAt:now,syncUpdatedAt:now});db.currentGoalieId=g.id;writeField(db);$('goalieId').value=g.id;$('goalieFormTitle').textContent='Edit Shared Goalie';renderGoalies();renderBenchmarking();refreshBackupGoalies();toast(`${g.name} saved to the shared directory`)});
  function statusText(g){if(g.benchmarkConsent==='opted_out')return'Opted out';if(g.benchmarkConsent==='opted_in'&&g.benchmarkLastSuccessfulUpload)return`Active · last upload ${new Date(g.benchmarkLastSuccessfulUpload).toLocaleString()}`;if(g.benchmarkConsent==='opted_in')return'Opted in · upload required';return'Not decided'}
  function renderBenchmarking(){const goalies=field().goalies;$('benchmarkList').innerHTML=goalies.length?goalies.map(g=>`<article class="benchmark-row"><div class="benchmark-meta"><b>${esc(g.name||'Unnamed Goalie')}</b><span>${esc(statusText(g))}</span></div><div class="benchmark-actions"><button class="secondary" data-consent="opted_in" data-goalie="${esc(g.id)}">Opt In</button><button class="secondary" data-consent="opted_out" data-goalie="${esc(g.id)}">Opt Out</button><a class="primary" href="field-hockey.html?tab=benchmarking&goalie=${encodeURIComponent(g.id)}">Open Upload Controls</a></div></article>`).join(''):'<div class="empty">Enroll a shared goalkeeper before activating benchmarking.</div>';document.querySelectorAll('[data-consent]').forEach(button=>button.addEventListener('click',()=>{const db=field(),g=db.goalies.find(x=>String(x.id)===String(button.dataset.goalie));if(!g)return;g.benchmarkConsent=button.dataset.consent;g.updatedAt=new Date().toISOString();writeField(db);renderBenchmarking();toast(g.benchmarkConsent==='opted_in'?`${g.name} opted in`:`${g.name} opted out`)}))}
  function suiteKeys(){return[...new Set([FIELD_KEY,TRIALS_KEY,...RECORDER_KEYS,...Object.keys(localStorage).filter(key=>/^(ddd_|hgs_|gsr_|hgt-)/i.test(key))])]}
  function keysForScope(scope){if(['field','directory','goalie'].includes(scope))return[FIELD_KEY];if(scope==='trials')return[TRIALS_KEY];if(scope==='recorder')return RECORDER_KEYS;return suiteKeys()}
  function backupData(scope){const stores={};keysForScope(scope).forEach(key=>{const raw=localStorage.getItem(key);if(raw!==null)stores[key]=raw});let goalie=null;if(scope==='directory'){const db=field();stores[FIELD_KEY]=JSON.stringify({...db,activeMatchId:'',goalies:db.goalies.map(g=>({...clone(g),matches:[]}))})}if(scope==='goalie'){goalie=field().goalies.find(x=>String(x.id)===String($('backupGoalie').value));if(!goalie)throw new Error('Choose a goalie to back up.');stores[FIELD_KEY]=JSON.stringify({goalies:[clone(goalie)],currentGoalieId:goalie.id,activeMatchId:''})}return{format:'data-driven-development-backup',schemaVersion:2,suiteVersion:SUITE_VERSION,scope,createdAt:new Date().toISOString(),goalieId:goalie?.id||null,stores}}
  function downloadJson(data,name){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function scopeLabel(scope){return({complete:'Complete suite',field:'Field Hockey',trials:'Field Hockey Trials',recorder:'Stats Recorder',goalie:'Single goalie',directory:'Goalkeeper directory'})[scope]||scope}
  function refreshBackupGoalies(){const selected=$('backupGoalie').value;$('backupGoalie').innerHTML=field().goalies.map(g=>`<option value="${esc(g.id)}">${esc(g.name||'Unnamed Goalie')}</option>`).join('');if([...$('backupGoalie').options].some(o=>o.value===selected))$('backupGoalie').value=selected}
  $('backupScope').addEventListener('change',()=>{$('backupGoalieWrap').classList.toggle('hidden',$('backupScope').value!=='goalie')});$('downloadBackup').addEventListener('click',()=>{try{const scope=$('backupScope').value,data=backupData(scope),date=new Date().toISOString().slice(0,10),suffix=scope==='goalie'?('_'+String(field().goalies.find(g=>String(g.id)===String($('backupGoalie').value))?.name||'Goalie').replace(/[^a-z0-9_-]+/gi,'_')):('_'+scopeLabel(scope).replace(/\s+/g,'_'));downloadJson(data,`Data_Driven_Development${suffix}_${date}.dddbackup`);toast(`${scopeLabel(scope)} backup downloaded`)}catch(error){alert(error.message)}});
  function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(new Error('The file could not be read.'));reader.readAsText(file)})}
  function normalizeBackup(data){if(data?.format==='data-driven-development-backup'&&data.stores&&typeof data.stores==='object')return data;if(data?.exportType==='SingleGoalieTransfer'&&data.goalie)return{format:'data-driven-development-backup',schemaVersion:1,scope:'goalie',createdAt:data.exportedAt||'',stores:{[FIELD_KEY]:JSON.stringify({goalies:[data.goalie]})}};if(Array.isArray(data?.goalies))return{format:'data-driven-development-backup',schemaVersion:0,scope:data.exportType==='MasterData'?'directory':'field',createdAt:data.exportedAt||'',stores:{[FIELD_KEY]:JSON.stringify(data)}};throw new Error('This is not a recognised Data Driven Development or Field Hockey backup.')}
  function backupCounts(data){const counts={stores:Object.keys(data.stores||{}).length,goalies:0,matches:0,trials:0,recorder:0};try{const db=JSON.parse(data.stores[FIELD_KEY]||'{}');counts.goalies=Array.isArray(db.goalies)?db.goalies.length:0;counts.matches=(db.goalies||[]).reduce((sum,g)=>sum+(g.matches||[]).length,0)}catch{}try{const tr=JSON.parse(data.stores[TRIALS_KEY]||'{}');counts.trials=Array.isArray(tr.goalies)?tr.goalies.length:0}catch{}counts.recorder=RECORDER_KEYS.filter(key=>data.stores[key]!==undefined).length;return counts}
  function renderPreview(data){const c=backupCounts(data),when=data.createdAt?new Date(data.createdAt).toLocaleString():'Date not recorded';$('backupPreview').className='backup-preview notice';$('backupPreview').innerHTML=`<b>${esc(scopeLabel(data.scope||'field'))} backup</b><span>Created ${esc(when)}</span><ul><li>${c.goalies} goalkeeper profile(s)</li><li>${c.matches} Field Hockey match(es)</li><li>${c.trials} Trials roster record(s)</li><li>${c.recorder} Recorder store(s)</li></ul><span>${c.stores} local data section(s) will be ${$('restoreMode').value==='merge'?'merged':'replaced'}.</span>`;$('restoreBackup').disabled=false}
  $('restoreFile').addEventListener('change',async()=>{pendingRestore=null;$('restoreBackup').disabled=true;const file=$('restoreFile').files[0];if(!file){$('backupPreview').className='backup-preview empty';$('backupPreview').textContent='Choose a backup to preview its contents.';return}try{pendingRestore=normalizeBackup(JSON.parse(await readFile(file)));renderPreview(pendingRestore);$('backupStatus').textContent='Preview ready. No data has been changed.'}catch(error){$('backupPreview').className='backup-preview empty inline-warning';$('backupPreview').textContent=error.message;$('backupStatus').textContent='';alert('Could not read backup: '+error.message)}});$('restoreMode').addEventListener('change',()=>{if(pendingRestore)renderPreview(pendingRestore)});
  function stamp(value){const n=Date.parse(value||'');return Number.isFinite(n)?n:0}function identity(item){if(item&&item.id!==undefined)return'id:'+item.id;if(item&&item.name)return'name:'+String(item.name).trim().toLowerCase()+'|'+String(item.dob||item.date||'');return null}
  function mergeArray(local,incoming,stats){const output=Array.isArray(local)?clone(local):[],index=new Map(output.map((item,i)=>[identity(item),i]).filter(x=>x[0]));for(const item of incoming||[]){const key=identity(item);if(!key){output.push(clone(item));stats.added++;continue}const at=index.get(key);if(at===undefined){index.set(key,output.length);output.push(clone(item));stats.added++;continue}const current=output[at],incomingTime=stamp(item.updatedAt||item.syncUpdatedAt||item.createdAt),currentTime=stamp(current.updatedAt||current.syncUpdatedAt||current.createdAt);if(incomingTime>=currentTime){output[at]=mergeObject(current,item,stats);stats.updated++}else stats.kept++}return output}
  function mergeObject(local,incoming,stats){if(Array.isArray(incoming))return mergeArray(Array.isArray(local)?local:[],incoming,stats);if(!incoming||typeof incoming!=='object')return incoming;const output=local&&typeof local==='object'&&!Array.isArray(local)?clone(local):{};Object.entries(incoming).forEach(([key,value])=>{if(Array.isArray(value))output[key]=mergeArray(output[key],value,stats);else if(value&&typeof value==='object')output[key]=mergeObject(output[key],value,stats);else output[key]=value});return output}
  function mergeStore(key,raw,stats){if(localStorage.getItem(key)===null){localStorage.setItem(key,String(raw));stats.storesAdded++;return}try{localStorage.setItem(key,JSON.stringify(mergeObject(JSON.parse(localStorage.getItem(key)),JSON.parse(String(raw)),stats)));stats.storesMerged++}catch{localStorage.setItem(key,String(raw));stats.storesUpdated++}}
  function confirmationCode(message){const code=String(100000+Math.floor(Math.random()*900000)),entered=prompt(`${message}\n\nType this 6-digit code to continue:\n\n${code}`);if(entered===null)return false;if(entered.trim()!==code){alert('The code did not match. Nothing was changed.');return false}return true}
  $('restoreBackup').addEventListener('click',()=>{if(!pendingRestore){alert('Choose and preview a backup file first.');return}const mode=$('restoreMode').value;if(mode==='replace'&&!confirmationCode('Replacing will overwrite every section included in this backup.'))return;const stats={added:0,updated:0,kept:0,storesAdded:0,storesMerged:0,storesUpdated:0};try{Object.entries(pendingRestore.stores).forEach(([key,value])=>{if(mode==='replace'){localStorage.setItem(key,String(value));stats.storesUpdated++}else mergeStore(key,value,stats)});$('backupStatus').textContent=mode==='replace'?`Replaced ${stats.storesUpdated} data section(s).`:`Merge complete: ${stats.added} records added, ${stats.updated} newer records applied, ${stats.kept} existing records retained across ${stats.storesAdded+stats.storesMerged+stats.storesUpdated} section(s).`;renderGoalies();renderBenchmarking();refreshBackupGoalies();toast('Backup restored successfully')}catch(error){alert('Could not restore backup: '+error.message)}});
  $('importRecorderMatch').addEventListener('click',async()=>{const file=$('recorderImportFile').files[0];if(!file){alert('Choose a Recorder match file first.');return}try{const payload=JSON.parse(await readFile(file)),match=payload.match||payload,sport=payload.sportType||match.sportType||'field_hockey';if(sport==='indoor_hockey')throw new Error('Indoor Hockey Stats is not active yet. This match has not been imported.');if(!Array.isArray(match.shots))throw new Error('No match shots were found in this file.');const db=field();let goalie=db.goalies.find(g=>String(g.id)===String(match.goalieId||payload.goalieId||''))||db.goalies.find(g=>String(g.name||'').trim().toLowerCase()===String(match.goalieName||'').trim().toLowerCase());if(!goalie){const name=match.goalieName||'Imported Goalie';if(!confirm(`${name} is not in the shared directory. Enrol this goalie and import the match?`))return;goalie={id:match.goalieId||uid(),name,dob:'',gender:'Male',ageGroup:'Not specified',teams:match.homeTeam?[match.homeTeam]:[],teamProfiles:match.homeTeam?[{id:uid(),name:match.homeTeam,sportType:'field_hockey',ageGroup:'Not specified',level:'Not specified',tier:'Not specified',isDefault:true}]:[],matches:[],centralProfile:true,updatedAt:new Date().toISOString()};db.goalies.push(goalie)}goalie.matches=goalie.matches||[];const matchId=match.id||uid();if(goalie.matches.some(m=>String(m.id)===String(matchId)))throw new Error('This match has already been imported.');const now=new Date().toISOString(),imported={...match,id:matchId,sportType:'field_hockey',opponentTeam:match.opponentTeam||match.opponent||'',opponent:match.opponentTeam||match.opponent||'',periods:Number(match.periods||match.periodCount||2),updatedAt:now,syncUpdatedAt:now};imported.name=imported.name||`${imported.date||now.slice(0,10)} - ${imported.homeTeam||'Home Team'} VS ${imported.opponentTeam||'Opponent'}`;goalie.matches.push(imported);db.currentGoalieId=goalie.id;writeField(db);$('recorderImportStatus').textContent=`Imported ${imported.name} for ${goalie.name}.`;toast('Recorder match imported')}catch(error){alert('Could not import Recorder match: '+error.message)}});
  $('clearData').addEventListener('click',()=>{const scope=$('clearScope').value;if(!confirmationCode(`Clear ${scopeLabel(scope)} data from this device? This cannot be undone without a backup.`))return;keysForScope(scope).forEach(key=>localStorage.removeItem(key));pendingRestore=null;renderGoalies();renderBenchmarking();refreshBackupGoalies();toast(`${scopeLabel(scope)} data cleared`)});
  let installPrompt=null;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('installButton').classList.remove('hidden')});$('installButton').addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installButton').classList.add('hidden')});
  clearGoalieForm();refreshBackupGoalies();const start=(location.hash||'').replace('#','');showPage(['goalies','benchmarking','backup','resources'].includes(start)?start:'home');if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));window.__dddSuiteTest={calculatedAgeGroup,normalizeBackup,backupCounts,mergeObject};
})();
