(()=>{
  'use strict';
  const FIELD_KEY='hockeyGoalieStatsV3';
  const TRIALS_KEY='hgt-data-driven-selection-v1';
  const RECORDER_KEYS=['gsr_v129_state','gsr_v128_state','gsr_v127_state','gsr_v126_state','goalieStatsRecorderMasterData','gsr_last_forced_refresh'];
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid=()=>{try{return 'id_'+crypto.randomUUID()}catch{return 'id_'+Date.now().toString(36)+Math.random().toString(36).slice(2)}};
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
  const field=()=>{const value=read(FIELD_KEY,{goalies:[]});if(!Array.isArray(value.goalies))value.goalies=[];return value};
  const writeField=value=>localStorage.setItem(FIELD_KEY,JSON.stringify(value));
  let toastTimer;
  function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
  function initials(name){return String(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
  function dobLabel(value){if(!value)return'Date of birth not recorded';const d=new Date(value+'T12:00:00');return Number.isNaN(d.getTime())?value:d.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
  function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+page));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('sidebar').classList.remove('open');location.hash=page==='home'?'':page;if(page==='goalies')renderGoalies();if(page==='benchmarking')renderBenchmarking();window.scrollTo(0,0)}
  document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',()=>showPage(x.dataset.page)));
  document.querySelectorAll('[data-go]').forEach(x=>x.addEventListener('click',()=>showPage(x.dataset.go)));
  $('menuButton').addEventListener('click',()=>$('sidebar').classList.toggle('open'));

  function renderGoalies(){const goalies=field().goalies;$('goalieList').innerHTML=goalies.length?goalies.map(g=>`<div class="goalie-row"><div class="goalie-avatar">${esc(initials(g.name))}</div><div class="goalie-main"><b>${esc(g.name||'Unnamed Goalie')}</b><small>${esc(g.gender||'Not specified')} · ${esc(dobLabel(g.dob))}</small></div><button class="secondary" type="button" data-edit-goalie="${esc(g.id)}">Edit</button></div>`).join(''):'<div class="empty">No shared goalkeepers enrolled yet.</div>';document.querySelectorAll('[data-edit-goalie]').forEach(button=>button.addEventListener('click',()=>editGoalie(button.dataset.editGoalie)))}
  function clearGoalieForm(){ $('goalieId').value='';$('goalieName').value='';$('goalieDob').value='';$('goalieGender').value='Male';$('goalieFormTitle').textContent='Enroll New Goalie';$('goalieName').focus() }
  function editGoalie(id){const g=field().goalies.find(x=>x.id===id);if(!g)return;$('goalieId').value=g.id;$('goalieName').value=g.name||'';$('goalieDob').value=g.dob||'';$('goalieGender').value=g.gender||'Male';$('goalieFormTitle').textContent='Edit Shared Goalie'}
  $('newGoalieButton').addEventListener('click',clearGoalieForm);
  $('goalieForm').addEventListener('submit',event=>{event.preventDefault();const db=field(),id=$('goalieId').value;let g=db.goalies.find(x=>x.id===id);if(!g){g={id:uid(),matches:[],teams:[],teamProfiles:[],benchmarkConsent:'undecided',benchmarkGoalieId:'goalie_'+uid(),centralProfile:true};db.goalies.push(g)}g.name=$('goalieName').value.trim()||'Unnamed Goalie';g.dob=$('goalieDob').value;g.gender=$('goalieGender').value;g.centralProfile=true;g.updatedAt=new Date().toISOString();db.currentGoalieId=g.id;writeField(db);$('goalieId').value=g.id;$('goalieFormTitle').textContent='Edit Shared Goalie';renderGoalies();renderBenchmarking();toast(`${g.name} saved to the shared directory`) });

  function statusText(g){if(g.benchmarkConsent==='opted_out')return'Opted out';if(g.benchmarkConsent==='opted_in'&&g.benchmarkLastSuccessfulUpload)return`Active · last upload ${new Date(g.benchmarkLastSuccessfulUpload).toLocaleString()}`;if(g.benchmarkConsent==='opted_in')return'Opted in · upload required';return'Not decided'}
  function renderBenchmarking(){const goalies=field().goalies;$('benchmarkList').innerHTML=goalies.length?goalies.map(g=>`<article class="benchmark-row"><div class="benchmark-meta"><b>${esc(g.name||'Unnamed Goalie')}</b><span>${esc(statusText(g))}</span></div><div class="benchmark-actions"><button class="secondary" data-consent="opted_in" data-goalie="${esc(g.id)}">Opt In</button><button class="secondary" data-consent="opted_out" data-goalie="${esc(g.id)}">Opt Out</button><a class="primary" href="field-hockey.html?tab=benchmarking&goalie=${encodeURIComponent(g.id)}">Open Upload Controls</a></div></article>`).join(''):'<div class="empty">Enroll a shared goalkeeper before activating benchmarking.</div>';document.querySelectorAll('[data-consent]').forEach(button=>button.addEventListener('click',()=>{const db=field(),g=db.goalies.find(x=>x.id===button.dataset.goalie);if(!g)return;g.benchmarkConsent=button.dataset.consent;g.updatedAt=new Date().toISOString();writeField(db);renderBenchmarking();toast(g.benchmarkConsent==='opted_in'?`${g.name} opted in`:`${g.name} opted out`)}))}

  function backupData(){const known=[FIELD_KEY,TRIALS_KEY,...RECORDER_KEYS],future=Object.keys(localStorage).filter(key=>/^(ddd_|hgs_|gsr_|hgt-)/i.test(key)),keys=[...new Set([...known,...future])],stores={};keys.forEach(key=>{const raw=localStorage.getItem(key);if(raw!==null)stores[key]=raw});return {format:'data-driven-development-backup',schemaVersion:1,suiteVersion:'1.0',createdAt:new Date().toISOString(),stores}}
  $('downloadBackup').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(backupData(),null,2)],{type:'application/json'}),a=document.createElement('a'),d=new Date().toISOString().slice(0,10);a.href=URL.createObjectURL(blob);a.download=`Data_Driven_Development_Backup_${d}.dddbackup`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Complete backup downloaded')});
  function confirmCode(){const code=String(100000+Math.floor(Math.random()*900000));const entered=prompt(`Restoring will replace the connected suite data on this device.\n\nType this 6-digit code to continue:\n\n${code}`);if(entered===null)return false;if(entered.trim()!==code){alert('The code did not match. Nothing was restored.');return false}return true}
  $('restoreBackup').addEventListener('click',()=>{const file=$('restoreFile').files[0];if(!file){alert('Choose a Data Driven Development backup file.');return}const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.format!=='data-driven-development-backup'||!data.stores||typeof data.stores!=='object')throw new Error('This is not a complete Data Driven Development backup.');if(!confirmCode())return;Object.entries(data.stores).forEach(([key,value])=>localStorage.setItem(key,String(value)));$('backupStatus').textContent=`Restored backup created ${new Date(data.createdAt).toLocaleString()}.` ;renderGoalies();renderBenchmarking();toast('Complete backup restored')}catch(error){alert('Could not restore backup: '+error.message)}};reader.readAsText(file)});

  let installPrompt=null;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('installButton').classList.remove('hidden')});$('installButton').addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installButton').classList.add('hidden')});
  const start=(location.hash||'').replace('#','');showPage(['goalies','benchmarking','backup'].includes(start)?start:'home');
  if('serviceWorker'in navigator&&location.protocol!=='file:')window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
})();
